name: Simple Commands
# on: [push]
jobs: 
 runs-shell-command:
  runs-on: ubuntu-latest
  steps:
   - name: echo a string
     run: echo "Hello World"
   - name: mulitline script
     run: |
      node -v
      npm -v 
   - name: python
     run: |
      import platform
      print(platform.processor())
     shell: python
 run-windows-command:
  runs-on: windows-latest
  needs: [runs-shell-command] 
  steps: 
   - name: Directory PowerShell
     run: Get-Location
   - name: Directory Bash
     run: pwd
     shell: bash
